### ISSUE TITLE
Wrap webR as a JupyterLite Kernel

### ISSUE THREAD

**Issue by psychemedia** [r-wasm/webr#1]
Hi

Loving this demo :-) But I guess it's limited in output terms, eg when generating graphical output?

It would be really interesting if this could be wrapped as a JupyterLite kernel, to provide access to R environments *in the browser* via [*JupyterLite*](https://github.com/jupyterlite) WASM powered Jupyter environment. This should (?) then provide support for graphical outputs (assuming the appropriate plotting libraries are available in the R distribution?)

I'm not sure what's involved (I'm an end-user rather than a developer), but there are some demo kernels for other languages in the `jupyterlite` Github org: https://github.com/orgs/jupyterlite/repositories

**Comment by georgestagg** [comment]
Graphical output actually works surprisingly well! PNG and JPEG output isn't available (R complains of the lack of X11) but you can write output to a PDF file, and then obtain the data through the Emscripten virtual filesystem and the `Module.FS` object. I have an example of that working in another environment, where R code is taken from an editor and the resulting plot is injected into the page in an iframe.

Probably the same idea using `FS` could be used to handle input and output of data files, such as CSVs.

Saying that, I expect more advanced graphics and I/O (e.g. `ggplot`) would be asking a little much right now. I've had to patch out loading dynamical libraries for the moment so until that is working the default libraries and base graphics is probably all that will work well.

**Comment by georgestagg** [comment]
Thanks for the tip about JupyterLite, I'll take a look!

**Comment by psychemedia** [comment]
Ah, ok re: getting graphical output. So for the png/jpeg there are some deeper dependencies required for *rendering* the output, rather than (*generating* it? If so, then maybe there is a way of returning the graphical output as encoded data and letting the JupyterLab machinery render it?

Handling data from files in JupyterLite is still a bit of an issue ( eg https://github.com/jupyterlite/jupyterlite/issues/119 ; data is stored in browser storage and it can be a faff getting it and out in the Python/pyolite/pyodide kernel at least.

**Comment by ryanlovett** [comment]
Here's a blog post describing the architecture of webassembly-based kernels, jupyterlite, and the Xeus library:
https://blog.jupyter.org/xeus-lite-379e96bb199d

> JupyterLite is a [JupyterLab](https://jupyter.org/) distribution that runs entirely in the web browser, backed by in-browser language kernels. [Xeus](https://github.com/jupyter-xeus/xeus) is C++ library for writing [Jupyter](https://jupyter.org/) kernels. In this blogpost we show how these two can work together.

**Comment by psychemedia** [comment]
There is also a [`xeus-cookiecutter`](https://github.com/jupyter-xeus/xeus-cookiecutter) for generating xeus-based Jupyter kernels that claims to include a wasm target which can be used to build a `jupyterlite-kernel`.

**Comment by SugarRayLua** [comment]
@psychemedia,

Fyi, Dr. Holzschu (developer of the mobile iOS Jupyter app, Carnets) had also expressed interest in being able to wrap a project like WebR in a Jupyter app when I wrote to him about webR:

https://holzschu.github.io/Carnets_Jupyter/

My interest remains in getting a fast port of R to work on mobile devices like the iPad (and not necessarily need to be shared in a cloud such as RStudio Cloud). Hopefully in the future Apple will unlock Hypervisor to work on its mobile M1 chips so that Linux could be run virtually on iPads which would then allow R to run locally and efficiently on iPads. 

Meanwhile, I got WebR working inside of the mobile Textastic app on my iPad and with the the .wasm file stored locally, it boots up quite rapidly and functions well:

https://youtu.be/V0bsWuGK8VI

:-)

**Comment by jiboncom** [comment]
Having a R kernel for JupyterLite would be amazing. Specially with the future release of VoilaLite, that would allow to quickly deploy R dashboards without a backend.

**Comment by twoxfh** [comment]
While jupyterlite would be cool too, [Starboard ](https://github.com/gzuidhof/starboard-notebook) might be easier and still gives you an interactive notebook.

**Comment by georgestagg** [comment]
A JupyterLite R kernel using webR is now available at https://github.com/r-wasm/jupyterlite-webr-kernel. It's still in early development, and so do take note of the **Limitations** section of the README file in that repo.

A demo with the webR kernel installed can be found at https://jupyter.r-wasm.org.

Closing this thread in favour of tracking issues with the JupyterLite kernel at the new repository.
