### ISSUE TITLE
Unable to make it work on production.

### ISSUE THREAD

**Issue by Anurodhyadav** [r-wasm/webr#150]
@georgestagg @lionel-

  I implemented a working application that runs R on browser using @r-wasm/webr package locally. Everything works fine there but i am getting this error after build.
![Screenshot 2023-02-16 at 16 05 38](https://user-images.githubusercontent.com/52653030/219346697-650ab740-f972-4f28-9313-76da7288e232.png)
I have also added the necessary share headers in the setupProxy.js and in the nginx server
This is the code in the nginx server

  location / {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
		add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
        	add_header 'Cross-Origin-Opener-Policy' 'same-origin';
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

Please let me know how can i resolve this?

**Comment by georgestagg** [comment]
Please be very wary when using the `@r-wasm/webr` npm package. Right now we are still preparing for the first release of webR, and the current npm packages availabe (with `alpha` in the version string) are for testing purposes and often go out of date from the latest build of webR.

Once we have released v0.1.0, we will push a version of the npm package that points to a fixed binary version of webR on CDN, which will make it safe to use.

In the meantime, if the above issue is not the problem, it looks like the webR communication channel cannot be created. Your headers in nginx look correct at first glance, but before trying anything else, please check that running `crossOriginIsolated` in the JS console in Dev Tools returns the value `true`. If the value `false` is returned the page is not Cross-Origin Isolated and most likely something has gone wrong serving the COOP/COEP headers.

**Comment by georgestagg** [comment]
The initial v0.1.0 release of the webR package is now available on NPM. Please update your package using `npm` and try running your app behind nginx once again.

If you are still having issues after updating the `@r-wasm/webr` package, let me know the result of the diagnostic test in my previous post (testing `crossOriginIsolated` in the console) in a comment and I will reopen the issue to investigate further.
