### ISSUE TITLE
`webr` exists on CRAN

### ISSUE THREAD

**Issue by barryrowlingson** [r-wasm/webr#165]
There's a package called `webr` on CRAN (since 2020). Even if `r-wasm/webr` can't go on CRAN because technical reasons, it is still potentially going to clash and confuse people. You might want to consider renaming this package (and maybe pushing a placeholder package to CRAN with the new name if CRAN are happy with that) before it gets too much use.

**Comment by lionel-** [comment]
Thanks for the heads up, we've already noticed this and considered whether to change the package name. We think the potential for confusion is low. I don't think placeholder packages are allowed on CRAN by the way (though they might have made an exception for this project).
