### ISSUE TITLE
Error: Dynamic require of "worker_threads" is not supported

### ISSUE THREAD

**Issue by awconway** [r-wasm/webr#167]
I was trying to run this in node but getting the following error when trying to import WebR.

```
import { WebR } from '@r-wasm/webr';
const webR = new WebR();

(async () => {
    await webR.init();

    let result = await webR.evalR('rnorm(10,5,1)');
    let output = await result.toArray();
    
    console.log('Result of running `rnorm` from webR: ', output);

})();
```

file:///workspaces/codespaces-blank/node_modules/@r-wasm/webr/dist/webr.mjs:12
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "worker_threads" is not supported
    at file:///workspaces/codespaces-blank/node_modules/@r-wasm/webr/dist/webr.mjs:12:9
    at file:///workspaces/codespaces-blank/node_modules/@r-wasm/webr/dist/webr.mjs:561:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.7.0

This was run in a fresh vscode codespace. Repo with reproducible example is [here](https://github.com/awconway/wasmr-test).

Sorry if I'm doing something wrong!

**Comment by georgestagg** [comment]
It looks like this is an instance of an issue with esbuild that https://github.com/evanw/esbuild/pull/2067 had attempted to solve.

Since that PR has been closed, we'll have to apply the workaround provided in the comments as part of our esbuild config in the next patch release. Apologies for the inconvenience in the meantime.

**Comment by georgestagg** [comment]
With the release of v0.1.1 of the `@r-wasm/webr` npm package, this should now work better.

I've put together an example of loading webR into node, for using both `require()` and `import` statements, here: https://github.com/georgestagg/webr-node-example

Please take a look and let me know if you have any further problems loading webR in node.
