### ISSUE TITLE
sf package

### ISSUE THREAD

**Issue by neocarto** [r-wasm/webr#169]
Are there any plans to add the sf package, which is the basis for all geographic analyses in R? It's probably complicated because there are some dependencies.  But is it planned? Possible?

**Comment by georgestagg** [comment]
Preliminary work on this has begun in #214, initially building for Wasm some system dependencies required for geospatial analysis (GDAL, PROJ).

It will probably still be a long time until the `sf` package is usable in webR, but we think in principle it should be possible once we have enough of the required system dependencies available for linking under Wasm.

**Comment by kadyb** [comment]
I just tested and works great!

<img src="https://github.com/r-wasm/webr/assets/35004826/c966b37f-2867-4763-b0df-0c2f3df52d65" width=80% height=80%>
