### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource

### ISSUE THREAD

**Issue by fortunewalla** [r-wasm/webr#175]
Hi, thanks for this new initiative. I tried to run `update.packages()` and got error. Is it a browser issue that I need to fix or a WASM issue?

OS: Win 10
browser: Firefox 110

### R CLI Message

```
Selection: 1
Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
  download from 'https://cloud.r-project.org/src/contrib/PACKAGES' failed
Warning message:
In download.file(url, destfile = f, quiet = TRUE) :
  URL https://cran.r-project.org/CRAN_mirrors.csv: Download failed. See the Javascript console for further information
```

### Javascript Console Message

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cloud.r-project.org/src/contrib/PACKAGES.gz. (Reason: CORS request did not succeed). Status code: (null).
```
### screenshot R CLI screen

![image](https://user-images.githubusercontent.com/7158596/225510409-3fdd810c-57e8-443b-bb72-1b591a289193.png)

### screenshot of JS Console Page

![image](https://user-images.githubusercontent.com/7158596/225510597-18ce9350-0a16-47bc-99d9-3b033d6ed7be.png)

**Comment by hrbrmstr** [comment]
There's no need to run `update.packages()` since WebR instances are very ephemeral. I honestly can't see any context where one would ever need to call that function in a WebR setting.

It sounds like the team did not "patch" that function to make sure to use the r-wasm.org repo, so I guess it technically is a bug. 

`https://cloud.r-project.org/src/contrib` has no WASM built packages.

`https://repo.r-wasm.org/` is the only one with them.

The error you're seeing is due to the security model of the web application context. And, I don't think that should change.

**Comment by georgestagg** [comment]
Bob is correct, webR packages do not act in the same way as R packages. They cannot be compiled from source within R and are instead pre-built and distributed in a binary repository for wasm packages. This means that not all of the normal R package management functions will work.

On first load of webR only the base R packages are installed. The latest version of a package built for webR can then be installed using the webR helper function `webr::install()`. This helper function defaults to using the wasm binary repository mentioned in the previous comment. For more information on R packages, see the documentation at https://docs.r-wasm.org/webr/latest/packages.html

I'm going to close this issue for now. We don't at the moment plan to fully support the standard R package installation procedures, such as `install.packages()` and `update.packages()` and probably won't be able to for some time. Such a scheme would require a compiler toolchain itself compiled for wasm and distributed in the browser. I think in these early days the combination of the existing webR package documentation and error message referencing the JavaScript console is a reasonable enough behaviour for the moment. Though, we may revisit this in future to show a more descriptive error message in the R console, once development of webR is more mature.
