### ISSUE TITLE
Problem loading packages

### ISSUE THREAD

**Issue by eteitelbaum** [r-wasm/webr#177]
Thanks for this project! 

I am trying to load packages into `webr`. When I run `webr::install("package")` I get the following error message:

Error: 'install' is not an exported object from 'namespace:webr'

I suspect that maybe this has to do with the webr support package? But I am not totally sure and [the link](https://docs.r-wasm.org/webr/latest/rapi) to that page appears to be broken.

**Comment by coatless** [comment]
@eteitelbaum please see my response in https://github.com/coatless/quarto-webr/issues/6#issuecomment-1475349244
