### ISSUE TITLE
How to read file while using WebRFS.

### ISSUE THREAD

**Issue by Anurodhyadav** [r-wasm/webr#184]
I have created the folder structure using WebRFS.
Here i have created a folder RCode.

This is the object that i generated when i use 
`await fs.lookupPath("/RCode");`

```
{
    "id": 1477,
    "name": "RCode",
    "mode": 16895,
    "isFolder": true,
    "contents": [
        {
            "id": 1478,
            "name": "src",
            "mode": 16895,
            "isFolder": true,
            "contents": [
                {
                    "id": 1479,
                    "name": "plot",
                    "mode": 16895,
                    "isFolder": true,
                    "contents": [
                        {
                            "id": 1482,
                            "name": "graph.R",
                            "mode": 33206,
                            "isFolder": false,
                            "contents": {}
                        }
                    ]
                },
                {
                    "id": 1480,
                    "name": "main.R",
                    "mode": 33206,
                    "isFolder": false,
                    "contents": {}
                },
                {
                    "id": 1481,
                    "name": "second.R",
                    "mode": 33206,
                    "isFolder": false,
                    "contents": {}
                }
            ]
        }
    ]
}
```

In the code editor that i am building i want to import a function `divide_by_two` from second.R in main.R using source.
main.R
    
```
source("second.R")
    Num <-2
    result <- divide_by_two(Num)
    print(result)
```

second.R
 
```
 divide_by_two <- function(x) {
      return(x/2)
    }
```

I get the following error when i run main.R

```
Error in file(filename, "r", encoding = encoding) :
cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
cannot open file 'second.R': No such file or directory
```

Although second.R is  created alongside main.R, it could not the file.  I tried using absolute path as well but nothing works. 

Please let me know how can i make it work.

@georgestagg @lionel-

**Comment by georgestagg** [comment]
Unfortunately, I am unable to reproduce this problem. I am able to successfully `source()` an R script that itself `source()`s another R script, once both scripts are added to the virtual file system.

Are you able to reduce your code down to a minimal reproducible example that demonstrates the problem? That would allow us to investigate further.

**Comment by ColinFay** [comment]
One possible explanation here is that you haven't put your working directory inside the RCode folder, so you can source the script, but the script tries to source a file that is not correct (for example, if you do `source("RCode/main.R")` then your R code will fail, as main.R should point to `"RCode/second.R"`.

You'll get the same message in plain old R:

```r
> fs::dir_tree("RCode")
RCode
├── main.R
└── second.R
> source("RCode/main.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'second.R': No such file or directory
```

Two possible fixes : 

- change the path in main.R to `RCode/second.R`
- Set your wd in the directory

**Comment by georgestagg** [comment]
Thanks for the tip, @ColinFay!

Since we haven't heard back in a while about this issue, I'm going to close it.

If you're still hitting this problem, please comment again here with a reproducible example, and I'll reopen the issue to investigate further.
