### ISSUE TITLE
Extend the webR console example - plot output with canvas

### ISSUE THREAD

**Issue by Polkas** [r-wasm/webr#194]
I've been working with the [webR console example](https://polkas.github.io/posts/webr/), and plot output still needs to be implemented. 
Only the [web app ](https://webr.r-wasm.org/latest/) supports the plot output, but its source seems hidden.
**I've added plot output support functionality with canvas in [my webR console](https://polkas.github.io/posts/webr/).** 
Expanding the documentation to make this clearer for others who want to do the same would be helpful. 
The [current example](https://polkas.github.io/posts/webr/) needs only around 15 additional code lines to add plot output support (without collapsible functionality).

**I would be happy to submit a PR to add this information** to the documentation (console example), but I wanted to check with you first to see if you would be interested in this. Please let me know if this sounds good and if you have any suggestions.

**Comment by hrbrmstr** [comment]
You can do, um, alot more https://webrider.rud.is/

**Comment by Polkas** [comment]
@hrbrmstr I used to work in scrum methodology and I assume my issue is clear and small as expected.
I think a lot more can be done for any product like referenced by you app. 
@hrbrmstr if you want to contribute I will recommend to create a few new issues like adding environment tab support or adding a code editor area. I assume my issue is clear and seems suited for current console example.

**Comment by georgestagg** [comment]
> Only the [web app](https://webr.r-wasm.org/latest/) supports the plot output, but its source seems hidden.

The source for the webR REPL demo app is at `src/repl/repl.ts`.

-----

@Polkas You're of course welcome to contribute and submit a PR to expand the documentation. We will review, but I can't think of a reason we wouldn't want to include this in principle.

I assume you are planning to expand [the interactive REPL example](https://docs.r-wasm.org/webr/latest/examples.html#creating-an-interactive-webr-repl-console). This example is intended to be a short introduction to integrating webR directly into an HTML document, and not intended to be as complete as the webR REPL or the app that @hrbrmstr posted. As such, please be careful so that any improvement you make is not too large in size on the resulting documentation page.

You may also want to link to [this documentation section](https://docs.r-wasm.org/webr/latest/communication.html#console) in your changes, which briefly mentions plotting and the `Console.canvas` property.

**Comment by Polkas** [comment]
I am preparing myself and I found out the fixed width:1008 and height:1008 for canvas plots. 
I see an improvement between webr [R4.1.2](https://github.com/r-wasm/webr/blob/8c1c8038e4d238e91ec141537de11e114a01da2b/patches/R-4.1.2/stage1.patch#L497-L498) and [R4.1.3](https://github.com/r-wasm/webr/blob/8c1c8038e4d238e91ec141537de11e114a01da2b/patches/R-4.1.3/emscripten-canvas-device.diff#L18-L20), and now the width and height are `canvas()` function arguments.

@georgestagg do we expect to support different plot dimensions, like adding R environment variables to make it possible to update plot dimensions?

I have an idea of how we can update the `canvas()` function from:

```r
canvas <- function(width=504, height=504, pointsize=12, bg="transparent", ...) {
   .External("canvas_new_device", width, height, pointsize, bg)
)
```

For something like the below function, with the usage of sys environment variables (`canvas_width` and `canvas_height`).
The sys environment variables can be set with `REnv` when initialization webr objects.

```r
canvas <- function(
  width = as.numeric(Sys.getenv("canvas_width", unset = 1008)) %/% 2, 
  height = as.numeric(Sys.getenv("canvas_height", unset = 1008)) %/% 2, 
  pointsize = 12,
  bg = "transparent",
   ...
) {
  .External("canvas_new_device", width, height, pointsize, bg)
}
```

**Comment by georgestagg** [comment]
I'm hesitant to link environment variables to the default argument values in this way, I think it would be different from how the default R graphics devices work?

There are other options if a different canvas size is required. A new device could be explicitly started with the required size,
```
> dev.new(width=256, height=256)
> plot(hist(rnorm(10000)))
> dev.off()
```

or you could override the default graphics device,
```
canvas2 <- function(...) { canvas(width=256, height=256, ...) }
> options(device=canvas2)
> plot(hist(rnorm(10000)))
```

P.S. The HTML canvas is rendered with a scaling of x2, to improve quality. This is why a width of 504 translates to a HTML `<canvas>` element size of 1008.

**Comment by Polkas** [comment]
Yes, I notice this x2 scaling factor as e.g., it makes it very hard to find out the source code:)

I very much like the recommendation to overwrite the `device.`. 
I just tested it, and it works perfectly fine. 
But then we require two actions from the end users (developers), run the r code for webr to overwrite the device (with proper dimensions) and change the `Console.canvas.width` and `Console.canvas.height` properties of the webR instance. It is not a problem, but we have to accept it.
The sys environment variables provided to REnv can be reused for canvas height and width so only one action is required.

I think I know everything and we can continue the discussion in the PR in the future.

**Comment by georgestagg** [comment]
I'm going to close this issue for now, in the interest of keeping things organised.

The current situation is that the [`Console` example](https://docs.r-wasm.org/webr/latest/examples.html#creating-an-interactive-webr-repl-console) does not go into detail about handling plotting, but there is [further documentation](https://docs.r-wasm.org/webr/latest/communication.html#console) on another page that explains there exists a `canvas` instance property on the class that will contain any resulting plots.

If you'd still like to expand the documentation with extra information to make plotting with `Canvas` clearer, please do feel free to make a PR and we'd be happy to take a look.
