### ISSUE TITLE
Wasi and wasix

### ISSUE THREAD

**Issue by gedw99** [r-wasm/webr#229]
I am doing s fair bit with wasi and also the very new wasix.

https://wasix.org/

most wasm runners are converging on wasix for standardisation 

wasix adds sockets and fs  and threading idioms.

so I wanted to ask if webr supports wasi yet so that we can do FAAS with it on servers or IOT devices ??

**Comment by georgestagg** [comment]
WebR does not yet support WASI, but it is on our radar and something that we're interested in looking at in the future. For the moment, we're mostly focusing on running webR in a web browser with its supporting JavaScript environment.

I'm going to close this issue as a duplicate, in favour of tracking WASI/WASIX support in #166. For more information about the current situation with regards to WASI support for webR, please [see my comment within that thread](https://github.com/r-wasm/webr/issues/166#issuecomment-1463657693).
