### ISSUE TITLE
WebR in MS Edge hangs?

### ISSUE THREAD

**Issue by gwd-at** [r-wasm/webr#235]
Anyone else having problems loading WebR in MS Edge Browser (on MS Windows 11 Pro).

Works on same PC with Firefox and Chrome but Edge gives 
`GET https://webr.r-wasm.org/favicon.ico 403`

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>TB2FD2NNZ7QDS1E0</RequestId>
<HostId>ckguSGmQR8Hu8H30+xYxxcqALTnAgkfiSxByX1WmDhMH1Jy52PGGaJsZcau6/Xzu0Hn6cdtHx0vt+8ur9CbuAg==</HostId>
</Error>
```
and (excerpt from Edge Developer Tools)
```
Uncaught (in promise) Exception {}
<html>
<body>
<!--StartFragment-->

Promise.then (async) |   |  
-- | -- | --
  | loadDylibs | @ | R.bin.js:1939
  | run | @ | R.bin.js:1939
  | runCaller | @ | R.bin.js:1939
  | removeRunDependency | @ | R.bin.js:1939
  | receiveInstance | @ | R.bin.js:1939
  | receiveInstantiationResult | @ | R.bin.js:1939
  | Promise.then (async) |   |  
  | (anonymous) | @ | R.bin.js:1939
  | Promise.then (async) |   |  
  | instantiateAsync | @ | R.bin.js:1939
  | createWasm | @ | R.bin.js:1939
  | (anonymous) | @ | R.bin.js:1939
  | loadScript | @ | compat.ts:28
  | (anonymous) | @ | webr-worker.ts:749
  | setTimeout (async) |   |  
  | init | @ | webr-worker.ts:747
  | onWorkerMessage | @ | webr-worker.ts:44
  | globalThis.onmessage | @ | webr-worker.ts:53

<!--EndFragment-->
</body>
</html>

```
Anyone else having issues?
Any remedies?
Thanks ...

**Comment by psychemedia** [comment]
Hanging for me in Chrome, Safari, Opera, Firefox today - stuck on "webR is downloading, please wait..."

**Comment by georgestagg** [comment]
> Hanging for me in Chrome, Safari, Opera, Firefox today - stuck on "webR is downloading, please wait..."

Can you try again for me, please? Sometimes if there are changes to Wasm binaries I have to manually invalidate the AWS cache the day after pushing an update to the build on the CDN at `/latest`. I've just done that, so hopefully should be working again in Safari, Chrome, Firefox.

**Comment by psychemedia** [comment]
All good for me now - thanks.

**Comment by georgestagg** [comment]
Tested and working this morning on MS Edge, v118.0.2088.61, Windows 11.
