### ISSUE TITLE
Error when compiling the R v4.3.0 package methods  with the current version of webr

### ISSUE THREAD

**Issue by jpjais** [r-wasm/webr#238]
I have the following error with the emscripten compilation of the methods package (R V4.3.0) :

```
/home/XXXX/webr/emsdk/upstream/emscripten/emcc -s SIDE_MODULE=1 -s WASM_BIGINT -Oz -s DECLARE_ASM_MODULE_EXPORTS=0 -shared -fwasm-exceptions -s SUPPORT_LONGJMP=wasm -L/home/XXXX/webr/webr/wasm/lib -s USE_FREETYPE=1 -o methods.so do_substitute_direct.o init.o methods_list_dispatch.o slot.o class_support.o tests.o utils.o
make[8]: Entering directory '/home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods/src'
make[8]: Leaving directory '/home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods/src'
make[7]: Leaving directory '/home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods/src'
make[6]: Leaving directory '/home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods'
make[6]: Entering directory '/home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods'
cp: cannot stat '/home/XXXX/webr/webr/host/R-4.3.0/lib/R/library/methods/libs/methods.so': No such file or directory

```

The library exists :

``` 
ls -l /home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods/src/methods.so
-rwxrwxr-x 1 XXXX XXXX 15428 XXX 15 09:12 /home/XXXX/webr/webr/R/build/R-4.3.0/build/src/library/methods/src/methods.so

```

and in the destination folder, there is a copy with wasm extension:

```
ls -l /home/XXXX/webr/webr/R/build/R-4.3.0/build/library/methods/libs/
total 16
-rwxrwxr-x 1 XXXX XXXX 15428 XXX 15 09:12 methods.so.wasm

```

Relaunching make, the error is different :

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/XXXX/webr/webr/R/build/R-4.3.0/build/library/methods/libs/methods.so':
  /home/XXXX/webr/webr/R/build/R-4.3.0/build/library/methods/libs/methods.so: invalid ELF header
Calls: loadNamespace -> library.dynam -> dyn.load
Execution halted

```

and there are now two copies of the library (they are identical) in the destination folder : 

```
[XXXX@rstudio webr]$ ls -l /home/XXXX/webr/webr/R/build/R-4.3.0/build/library/methods/libs/
total 32
-rwxrwxr-x 1 XXXX XXXX 15428 XXX 15 09:18 methods.so
-rwxrwxr-x 1 XXXX XXXX 15428 XXX 15 09:12 methods.so.wasm`

```
I suppose it' a problem with the methods package Makefile, but  I haven't been able to identify the error.

**Comment by georgestagg** [comment]
Interesting, I can see the `emcc` command contains `-o methods.so`, but it looks like Emscripten is outputting a file `methods.so.wasm`.

Can you let me know which version of Emscripten you have installed? The first line of `emcc -v` should tell you. For comparison, it looks like I'm running v3.1.37.

**Comment by jpjais** [comment]
```
>emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.43 (a6b8143cf3c1171db911750359456b15a8deece7)
clang version 17.0.0 (https://github.com/llvm/llvm-project 71513a71cdf380efd6a44be6939e2cb979a62407)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/XXX/webr/emsdk/upstream/bin

>node -v
v20.3.1
```
EM_NODE_JS has been also defined

**Comment by georgestagg** [comment]
Thanks for the update, probably one of our `Makefile`s needs tweaking to be aware of and handle the case where `lib64` is used.

I'd like to try to reproduce your environment for testing, could you please tell me your OS and its version? Or if you're running this somewhere like Docker, which image you're using? Thanks.

**Comment by jpjais** [comment]
It's a VM with AlmaLinux 8.7.

**Comment by jpjais** [comment]
the issue is related to the [multilib](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Multilib) architecture of the FEDORA/RHEL derivative distributions. We have to set the ```LIBnn``` environment variable to  ```lib``` for the R stage 1 compilation configure. This can be done in the [Makefile](https://github.com/r-wasm/webr/tree/main/R) in the R directory.

**Comment by georgestagg** [comment]
Aha, great debugging work! I was able to set up an AlmaLinux environment in Docker, but I'm running an `arm64` machine and I guess multilib is not a factor there since webR seemed to build OK in my testing.

By the way, the file `~/.webr-config.mk` is included by default in that `Makefile` as a way to configure local overrides. You might be able to handle the required change by setting something like `export LIBnn=lib` in your own `.webr-config.mk` file, rather than editing the `Makefile` directly. Though, it would be better of course if this tweak were not required at all.

Our stage 1 build of R is only used for part of building the stage 2 Wasm binaries, it is not actually installed elsewhere in the system. So, I think we can set things for everyone so that `lib` is always used, rather than `lib64`. In fact, it seems that we currently depend on it to be that way.  I'll do some testing and make a change to add `LIBnn=lib` to the `configure` arguments if everything seems to work OK.
