### ISSUE TITLE
`webr::install()` breaks on old versions of webR if packages are updated

### ISSUE THREAD

**Issue by georgestagg** [r-wasm/webr#245]
Probably this can be fixed by updating `webr::install()` so that `utils::available.packages()` is used with a `contriburl` pointing to the binary directory. That way the package list returned by `available.packages()` is specific to the version of R that's running.

See r-wasm/webr-repo#29.

**Comment by coatless** [comment]
@georgestagg I'm not sure what the repo structure being used by <https://repo.r-wasm.org/>. But, shouldn't the binaries being generated already be versioned like:

```
- www (e.g. /)
  |- bin
     |- macosx
        |- contrib
           |- 4.1
              |- package_1.0.0.tgz
              |- PACKAGES
              |- PACKAGES.gz
           |- 4.3
              |- package_1.0.0.tgz
              |- PACKAGES
              |- PACKAGES.gz
  |- src
     |- contrib
        |- package_1.0.0.tar.gz
        |- PACKAGES
        |- PACKAGES.gz
```

where the `PACKAGES.gz`/`PACKAGES` would be obtained via:

```r
tools::write_PACKAGES("~/path/to/bin/macosx/contrib/4.1")
```

**Comment by coatless** [comment]
Thanks for the detailed response! I think one additional question I would have here is should the `[version]` component be more along the lines of `[r-version]-[webr-version]`, e.g. `4.1-0.1.0`? This would potentially allow for changes if the Emscripten and/or the compiler shift between releases. (The downside is this increases the number of R package binaries.)

I wouldn't worry too much about the redirect at the moment. I think a huge surge of interest will come after posit::conf(2023). Do you know if you're aiming to release `v0.2.0` before then?

**Comment by georgestagg** [comment]
>should the [version] component be more along the lines of [r-version]-[webr-version], e.g. 4.1-0.1.0?

Perhaps... Though I'd rather not stray too far from the usual CRAN structure for the moment. My current plan is to avoid updating the version of Emscripten that we're using to build the public distributions of webR and its packages between major versions of R, so as to avoid that issue. In any case, from experimentation it seems like small changes to Emscripten do not always cause issues, the Emscripten team just don't guarantee the ABI compatibility for sure.

> Do you know if you're aiming to release v0.2.0 before then?
Yes, it should be very soon. v0.1.1 should continue to work if there is no time for you to upgrade and test quarto-webr for 0.2.0 (At the very least, handling plotting messages will need to be reworked, let me know if you need help after release).
