### ISSUE TITLE
Can webR open a new html window (e.g. using the "reactable" library")?

### ISSUE THREAD

**Issue by SugarRayLua** [r-wasm/webr#248]
Hi.

Your team continues to do really amazing work with WebR. Now appears to be a very usable IDE!

I also saw that you've added a lot of packages which is very helpful. Specifically, I saw that you added reactable which I've been waiting for since with WebR one cannot open up an X window and thus one is unable to quickly use "View" to see one's dataframe in a convenient spreadsheet view. The reactable library provides some of the same functionality by allowing one to view one's dataframe as an html widget. Although reactable seemed to load up fine on webR, I couldn't get it to open and display a dataframe on my browser (Safari, mobile iOS on iPad).

Command given:
library(reactable)
reactable(mtcars)

No error or new html window with mtcars dataframe in it displayed.

Fyi.

**Comment by SugarRayLua** [comment]
Thank you for looking into this issue and considering a remedy. :-)

**Comment by timelyportfolio** [comment]
Another potential (but inelegant) approach to `htmlwidgets` with `webR` would be to let `R` instantiate/construct the widget and then JS (with correct dependencies loaded) build through `htmlwidgets.js`.  Here is an old [post](https://buildingwidgets.com/post_look_ma_no_R/) demonstrating the approach (long before webR).  I'll try to build this out a little with `webR`.

**Comment by timelyportfolio** [comment]
Using a little easier approach than the [post](https://buildingwidgets.com/post_look_ma_no_R/), here is an example how we might include `reactable` htmlwidget from `webR`.  The most difficult part is manually handling/adding the dependencies. These should live in the `webR` virtual file system, so I am wondering if we could use/add from there.  Also reminds me of https://github.com/ramnathv/htmlwidgets/issues/249.

[example on stackblitz](https://stackblitz.com/edit/web-platform-awfyt2?file=main.js)

![image](https://github.com/r-wasm/webr/assets/837910/980fc36e-73e2-4f71-9619-020ae92e0853)

**Comment by georgestagg** [comment]
Fixed in #449. Tracking `browseURL()` in #295.

**Comment by SugarRayLua** [comment]
Thank you very much! 😊
