### ISSUE TITLE
Interactive Rmd on GitHub Pages?

### ISSUE THREAD

**Issue by kadyb** [r-wasm/webr#253]
I'm very curious about one thing. In the far future, would it be possible to automatically create an interactive notebook (Rmd or Quarto) in a simple way that could be hosted on GitHub Pages? For example by adding a YAML header `interactive: TRUE` or something.

**Comment by kadyb** [comment]
Here is the extension to Quarto that works like this: https://github.com/coatless/quarto-webr

**Comment by jhk0530** [comment]
Hello, 

I don't know if this is what you were expecting, 

You can make quarto page webR included and deploy it with github page.

Here is example [page](https://jhk0530.github.io/webR/) and [repo](https://github.com/jhk0530/wasmR) I made.

**Comment by georgestagg** [comment]
> [Is it] possible to automatically create an interactive notebook (Rmd or Quarto) in a simple way that could be hosted on GitHub Pages?

As far as I know, using the latest version of webR and `quarto-webr` should work now when deploying to GitHub Pages, by setting `channel-type: "post-message"` in the YAML header. James' documentation at https://quarto-webr.thecoatlessprofessor.com/qwebr-communication-channels.html is very good and explains more details.

I'm going to close this issue, recommending indeed that Quarto with `quarto-webr` is the current best practice for creating interactive documents with webR.
