### ISSUE TITLE
Shimming install.packages ?

### ISSUE THREAD

**Issue by jeroen** [r-wasm/webr#262]
It might be helpful for new users if `install.packages()` is shimmed using `webr::install()`. Right now, the first thing people may want to try in the demo results in an error message that is difficult to understand.

<img width="697" alt="Screenshot 2023-08-31 at 2 47 39 PM" src="https://github.com/r-wasm/webr/assets/216319/b3e49976-1249-4bf0-93d6-46209c4096b2">

There is a precedent in the RStudio IDE of shimming install.packages:

```r
> install.packages
function (...) 
.rs.callAs(name, hook, original, ...)
<environment: 0x7feac5a466a0>
```

**Comment by ColinFay** [comment]
+1 on this

**Comment by ColinFay** [comment]
Note, `{renv}` also shims `install.packages` : https://github.com/rstudio/renv/blob/main/R/shims.R#L4

**Comment by ColinFay** [comment]
@georgestagg happy to try and draft a PR for this if you want this feature

**Comment by georgestagg** [comment]
Sure, contributions are welcome and I think this sounds like a reasonable feature.
