### ISSUE TITLE
Consider simpler example for plotting

### ISSUE THREAD

**Issue by JosiahParry** [r-wasm/webr#278]
Currently the only example for managing plotting is fairly "complex" in that it uses an async loop to draw 18 plots. It would be quite nice if there were simpler examples that address "Drawing the bitmap image data." Simpler examples could more closely resmbles plotting in base R eg `y <- rnorm(100); plot(1:100, y)`.

Or examples illustrating the callbacks from the console would be quite useful too as the [documentation](https://docs.r-wasm.org/webr/latest/api/js/interfaces/WebR.ConsoleCallbacks.html#canvasimage) for these are fairly sparse.

**Comment by JosiahParry** [comment]
Finding https://github.com/r-wasm/webr/blob/2537c29aac3ab80555eb90bd3ef4ab56c1fdfaa9/src/examples/plot/plot.js to be helpful

**Comment by georgestagg** [comment]
There's also a slightly simpler example at https://docs.r-wasm.org/webr/latest/examples.html#plotting-with-a-html-canvas-element, though it's not obvious that a plotting example exists there.

Probably that example should be moved or duplicated into the Plotting page.

**Comment by JosiahParry** [comment]
Here's an example that I'm using (to make a GH issue with 🙃, incoming!!) that might be a bit simpler? It connects the console with a canvas (i think?).

```html
<html>
  <head>
    <title>WebR Test Console</title>
  </head>
  <body>
    <div>
      <canvas width="500" height="500" id="plot-canvas"></canvas>
    </div>
    <div>
      <pre><code id="out">Loading webR, please wait...</code></pre>
      <input spellcheck="false" autocomplete="off" id="input" type="text">
      <button onclick="globalThis.sendInput()" id="run">Run</button>
    </div>
    
    <script type="module">
      /* Create a webR console using the Console helper class */
      import { Console } from 'https://webr.r-wasm.org/latest/webr.mjs';
      const webRConsole = new Console({
        stdout: line => document.getElementById('out').append(line + '\n'),
        stderr: line => document.getElementById('out').append(line + '\n'),
        prompt: p => document.getElementById('out').append(p),
        canvasImage: ci => {
          var canvas = document.getElementById("plot-canvas")
          var ctx = canvas.getContext('2d');
          ctx.reset();
          ctx.drawImage(ci, 0, 0);
    },
      });
      webRConsole.run();
      
      /* Write to the webR console using the ``stdin()`` method */
      let input = document.getElementById('input');
      globalThis.sendInput = () => {
        webRConsole.stdin(input.value);
        document.getElementById('out').append(input.value + '\n');
        input.value = "";
      }
      
      /* Send input on Enter key */
      input.addEventListener(
        "keydown",
        (evt) => {if(evt.keyCode === 13) globalThis.sendInput()}
      );
    </script>
  </body>
</html>
```

**Comment by georgestagg** [comment]
The documentation now contains several examples of plotting with varying levels of complexity.

"Simple" examples can now be found [here](https://docs.r-wasm.org/webr/latest/examples.html#plotting-with-a-html-canvas-element), and [here](https://docs.r-wasm.org/webr/latest/plotting.html#plotting-from-the-console), so I'll close this as completed.
