### ISSUE TITLE
find which packages are missing

### ISSUE THREAD

**Issue by bugzpodder** [r-wasm/webr#280]
currently I use a home grown regex to parse the user's code and find out the packages they need to install:
```
/^^(?:\\n)?\s*(?:library|require)\(["']?(?<dependency>[\w.-]+)/gm;
```
and the results are fed into: ```  await webR.installPackages(packages, true);```
Is there a better way to do this?  pyodide has a find_imports function that relies on parsing ast.

aside: I love how 0.2.1 supports a postMessage channelType.  I tested it out and it works flawlessly.  I really hated serving serviceworker/worker files when there is a lack of crossOriginIsolated support

**Comment by coatless** [comment]
I think you're looking for functionality similar to Pyodide's [loadPackagesFromImports()](https://github.com/pyodide/pyodide/blob/e2c2884e7a9afd90b23849220ee578bd2d523458/src/js/api.ts#L161), which is calling [find_imports](https://github.com/pyodide/pyodide/blob/e2c2884e7a9afd90b23849220ee578bd2d523458/src/py/_pyodide/_base.py#L583) to walk the AST to identify the Python package names? 

If so, you're in luck! I've been toying around with that to avoid needing to specify a `packages` key. The following "works" using only base R functions (e.g. no [`lobstr::ast()`](https://rdrr.io/pkg/lobstr/man/ast.html) or [`rlang`](https://rlang.r-lib.org/) functions)  to detect package names in `require()` and `library()` function calls. 

That said, it doesn't have logic to detect package loading using `requireNamespace()`/`loadNamespace()`, namespace function calls (e.g. `pkg::fun()`/`pkg:::fun()`), if the package name is given as a variable (`x = 'mypkg'; require(x, character.only = TRUE)`), or another possible way. This also isn't setup to check to see if the package is available inside the webR repository.

``` r
# Function to extract package names from R code
extract_package_names <- function(code) {
  # Parse the code into an expression
  ast_expr <- parse(text = code, encoding = "UTF-8")
  
  # Create an environment to store package names
  package_name_env <- new.env(parent = emptyenv())
  
  # Define a way to walk the expression tree
  recursive_walk_ast <- function(node, f) {
    # Evaluate node with function
    f(node)
    
    # Check if its recursive and move further down the tree.
    if (is.recursive(node)) {
      for (i in seq_along(node)) {
        recursive_walk_ast(node[[i]], f)
      }
    }
  }
  
  # Function to recursively extract package names
  library_and_require_pkg_names = function(node) {
    # Check if the expression is a function call
    if (!is.call(node)) {
      return(FALSE)
    }
    
    # Check if the function name is 'library' or 'require'
    if (!as.character(node[[1]]) %in% c("library", "require")) {
      return(FALSE)
    }
    
    # Convert call to match library function parameters with silent operations
    # e.g. library(pkg_name) -> library(package = pkg_name)
    library_call = tryCatch(
      withCallingHandlers(
        # Make sure to compare against base to avoid any webR shims.
        match.call(base::library, node),
        warning = function(e)
          invokeRestart("muffleWarning"),
        message = function(e)
          invokeRestart("muffleMessage")
      ),
      error = identity,
      warning = identity
    )
    
    # Check to see if the converted library call is valid or errored
    if (inherits(library_call, "error")) {
      return(FALSE)
    }
    
    # Check to see if the package has one entry
    if (length(library_call$package) == 1) {
      # Cast to character in the case of a symbol being present.
      # Store package name in environment
      assign(as.character(library_call$package), TRUE, envir = package_name_env)
      return(TRUE)
    }
    
    # No package name was detected.
    return(FALSE)
  }
  
  # Extract package names
  recursive_walk_ast(ast_expr, library_and_require_pkg_names)
  package_names <- ls(envir = package_name_env)
  
  # Return the detected package names
  return(package_names)
}
```

Some quick demo code... 

```r
# Example R code
code <- "
library(dplyr)
require(ggplot2)

my_function <- function() {
  require(lubridate)
}

library(tidyr)
"

# Call the function to extract package names
package_names <- extract_package_names(code)

# Print the detected package names
cat("Detected package names:", package_names, "\n")
#> Detected package names: dplyr ggplot2 lubridate tidyr
```

**Comment by bugzpodder** [comment]
@coatless sweet!
I tried this and it worked for the most part, unfortunately there was this single example I had tried that had ```
webr::install("ggplot2")
```
in it and it broke the parser
```
Error: unexpected symbol in:
"code <- "
webr::install("ggplot2"
Error in if (!as.character(node[[1]]) %in% c("library", "require")) { : 
  the condition has length > 1
```

I ended up just use your snippet and then try/catch and fall back to my old snippet!
