### ISSUE TITLE
Enhancement: RPostgreSQL for webR

### ISSUE THREAD

**Issue by SugarRayLua** [r-wasm/webr#287]

**Comment by georgestagg** [comment]
Thanks for the feature request!

In principle, this depends on external networking for connecting to databases such as postgreSQL. As such, the issue is also covered by #129. I'm going to close this one in favour of tracking things there.

**Comment by SugarRayLua** [comment]
Thank you for the update and considering the request :-)

**Comment by gregvolny** [comment]
> Thanks for the feature request!
> 
> In principle, this depends on external networking for connecting to databases such as postgreSQL. As such, the issue is also covered by #129. I'm going to close this one in favour of tracking things there.

Others found some working solution for networking/Database access from the browser. Please take a look on this repo: https://github.com/stack-auth/pgmock

**Comment by SugarRayLua** [comment]
Wonderful, thanks!
