### ISSUE TITLE
[not an issue] R playground using WebR

### ISSUE THREAD

**Issue by hatemhosny** [r-wasm/webr#288]
Thank you for such a great project.

Excuse me for creating an issue. You do not have discussions enabled.

Please allow me to introduce [LiveCodes](https://livecodes.io), a [feature-rich](https://livecodes.io/docs/features/), [open-source](https://github.com/live-codes/livecodes), [client-side](https://livecodes.io/docs/why/#client-side), code playground that supports [80+ languages and frameworks](https://livecodes.io/docs/why/#language-support) (including [R](https://livecodes.io/docs/languages/r/) and [Python](https://livecodes.io/docs/languages/pyodide/)). The [announcement post](https://blog.livecodes.io/introducing-livecodes/) gives a general overview.

R is supported in LiveCodes using **WebR**.

R starter template is available for a quick start:  https://livecodes.io/?template=r  
(see all [starter templates](https://livecodes.io/?new)).

You can start an empty R project using this link: https://livecodes.io/?r

Projects can be [shared](https://livecodes.io/docs/features/share/), [exported](https://livecodes.io/docs/features/export/) and [deployed](https://livecodes.io/docs/features/deploy/) (to GitHub Pages), in addition to a lot more [features](https://livecodes.io/docs/features/).

There is even a free [AI code assistant](https://livecodes.io/docs/features/ai) (similar to GitHub Copilot).

Playgrounds can be [embedded](https://livecodes.io/docs/features/embeds) in any webpage, using a powerful, yet easy-to-use, [SDK](https://livecodes.io/docs/sdk).

This is an example for an embedded R playground:

```html
<div id="container"></div>

<script type="module">
  import { createPlayground } from 'https://unpkg.com/livecodes';

  createPlayground('#container', {
    params: {
      r: 'head(iris)\n',
    },
  });
</script>
```
[Preview](https://livecodes.io/?mode=result&x=code/N4IgLglmA2CmIC4QCUAEsC2AjWATXeqADtAIYCeA5gE4D2ArgHa6oEa0gA0IBAzgMbUIRSLUaIQXcKUq9EAbQC63Uv0gA3WAFFcUWtQkZS1ANb0iUo6fOJQZRpXoz4SABZgM0KfzFhYjMAkAHl11VAhcAF4AHRAfANIIRlhqWIA+IIB6ULTo1MY86MYggSERVDByIlgYkHZcejh0wsZUcIwifTBUYFRBWFI-AAUyKjomFgBfVAAzOgxUAHJ3MCJeBEzMpiITSgA6HwxM6AhNHz5FgG4Wlrb+wdgRihoGZgAKRYBieLBE5OpFpwerc2sRjKQMOtgflQaDqAglq4Brg3hAhLwAJTRIqAkFtSacEGTDHXfJZUrCMBpEAEkC8SpwWwgeyOZwSfi8OTcH7+QJILC0XDkaFFNpWShJAC0YFoRARAFYAAxEAAepKKkxp3ApIiZLKclBcIAAVqR1KQdYFub5eRItXSGbBeEjYGA5AglNrBJT3Z64pyhtQna67dwiHR+E7ePpfco4vR6bQMABlV2QBzu4C0iAdLqZ2mVar57h+emZ5mkBwGo2Fp3e3XWgK2pD2zTUXgQMQSACM8ppQA)

Please refer to the [SDK documentations](https://livecodes.io/docs/sdk) for details.

Supported R packages are [loaded automatically](https://livecodes.io/docs/languages/r/#loading-packages) when used in code, without an explicit install.

R output and plots are rendered, by default, in `document.body`. However, [output rendering](https://livecodes.io/docs/languages/r/#output-rendering) can be configured.

Comprehensive [documentations](https://livecodes.io/docs/) are available with live demos, code samples and screenshots.

LiveCodes is [open-source](https://github.com/live-codes/livecodes), free with unlimited usage, no ads and no account required. It can be easily [self-hosted](https://livecodes.io/docs/features/self-hosting) (if you want), and can be used for commercial projects ([MIT license](https://livecodes.io/docs/license)).

Disclosure: obviously, I'm the author of LiveCodes.

I thought you would be interested to know about [LiveCodes](https://livecodes.io). Otherwise, please feel free to close this.

**Comment by georgestagg** [comment]
Very neat! It's always so great to see webR as a useful part of wider projects and applications.

I'm going to close the issue, just to keep things tidy, but thanks for sharing the details of your project with us!
