### ISSUE TITLE
Specifying line type in the webR Canvas graphics device does not work

### ISSUE THREAD

**Issue by bugzpodder** [r-wasm/webr#289]
Not sure if its discrependency is intended but i am seeing a very slight difference in the following code in RStudio vs webR

```
library('ggplot2')
ggplot() +
    geom_hline(aes(yintercept = 10, linetype = "p-value Threshold"), color = "green") + 
    geom_vline(aes(xintercept = 1, linetype = "Upper FC"), color = "blue") + 
    geom_vline(aes(xintercept = -1, linetype = "Lower FC"), color = "red")

```
RStudio shows the lines as dashed and webR (using plot()) draws the line as solid.  
<img width="1658" alt="Screenshot 2023-10-05 at 5 03 29 PM" src="https://github.com/r-wasm/webr/assets/14841421/4450aa0b-b055-405d-ad8e-df7bca7f0afd">

**Comment by georgestagg** [comment]
Thanks, this looks like a more general bug with line types in the Canvas graphics device!

For example, the code

```
plot(1:10, 1:10, type="l", lty=2)
```

should produce a dashed line, but instead produce a solid line.
