### ISSUE TITLE
Bootstrap a custom namespace

### ISSUE THREAD

**Issue by bugzpodder** [r-wasm/webr#291]
What is the preferred way of bootstrapping a custom namespace.
I am new to R and did some investigations with ChatGPT and Google but couldn't find a solution (eg [here](https://www.paulamoraga.com/blog/2022/04/12/2022-04-12-rpackages/))

`devtools::load_all()` might work but it seems fairly slow to get devtools installed in webR.

I would like to setup an internal namespace in webR, something like:

```
mypackage/
  NAMESPACE
  R/
    file.R
```

and in webR, import `mypackage` and call something like `mypackage::foo`

**Comment by bugzpodder** [comment]
was able to get [box](https://cran.r-project.org/web/packages/box/index.html) and [modules](https://cran.r-project.org/web/packages/modules/index.html) working

**Comment by ColinFay** [comment]
@bugzpodder this might also interest you https://colinfay.me/using-own-functions-in-webr-node-js/
