### ISSUE TITLE
Bug in webr::install for length repos > 1

### ISSUE THREAD

**Issue by jeroen** [r-wasm/webr#299]
We’ve been doing some experimental building of wasm binaries in r-universe. There is a bug in `webr::install` when options(repos) is of length > 1. For example when we do:

```r
webr::install('dplyr', repos = c('https://tidyverse.r-universe.dev', 'https://repo.r-wasm.org'))
```

R does not install dependencies from the second repo.

**Comment by georgestagg** [comment]
Confirmed. Issue is at https://github.com/r-wasm/webr/blob/3ba2e01d6466bd82b7403be7280a783971e99817/packages/webr/R/install.R#L21

**Comment by ColinFay** [comment]
It feel like given that `info <- utils::available.packages(contriburl = contrib)` can take a vector of urls, removing the `[[1]]` from the `sprintf` works? 

<img width="779" alt="Screenshot 2023-10-19 at 21 17 55" src="https://github.com/r-wasm/webr/assets/17936236/a0830262-5e11-464e-9988-b043430c4d6a">

See PR #305
