### ISSUE TITLE
Error passing large array from JS to WebR

### ISSUE THREAD

**Issue by chrispahm** [r-wasm/webr#303]
Hey 👋
First of all thanks for the amazing work you put into creating webR!

I’m trying to pass a large array from JS to the R context using `new webR.RObject(large_array)`. However, it fails with a simple error message stating “Error”, repeated calls suggest that memory is out of bounds.

I'm using the `PostMessage` communication channel.

Here’s a reproducible example of the bug on Observable:
https://observablehq.com/d/9be88c7a4d7b0edd

Thanks for your help!

**Comment by georgestagg** [comment]
Your example URL gives "Sorry, but we can’t find that page right now" for me. Perhaps it needs to be made public?

**Comment by chrispahm** [comment]
Sorry, I broke the link when typing this issue on the phone 🙈 Updated the link in the original post (https://observablehq.com/d/9be88c7a4d7b0edd)

**Comment by georgestagg** [comment]
Thanks for reporting this, I think I can see the bug.

I think the code that converts an arbitrary JS array into a R object needs tightening up.
https://github.com/r-wasm/webr/blob/52e1f20ae0f543649d72cff89e686f0186124824/src/webR/robj-worker.ts#L126-L138
At the very least, it should check to see if all elements are the same and skip the `c()` call construction if they are, instead just creating the resulting object directly.

In the meantime, I think using `RDouble` should work OK, or reworking the input to `RObject` to tell it that the input is an array of doubles:

https://observablehq.com/d/c60eb6ea40dfe8c6

**Comment by chrispahm** [comment]
Awesome! That's a great temporary fix, however I'm wondering how I could use this to populate a global variable
```js
const col = diamonds.map((row) => row.carat);
await webR.objs.globalEnv.bind("carat", col);
```

**Comment by georgestagg** [comment]
Try,

```
const col = await new webR.RDouble(diamonds.map((row) => row.carat));
await webR.objs.globalEnv.bind("carat", col);
```

**Comment by chrispahm** [comment]
Thanks for the quick fixes! I've been using this to transfer JS "dataframes" (arrays of objects) to R so they can be used in function calls to lm, glm etc. 

Droppping it here in case someones needs a similar function and stumbles upon it:
```js
async function jsonToDataframe(json, globalVarName = "") {
  if (!globalVarName) {
    globalVarName = "dataVar_" + makeid(10);
  }
  if (!json)
    throw new Error(
      "No input data provided. Input data has to be an array of objects."
    );
  if (
    Array.isArray(json) &&
    typeof json === "object" &&
    !Array.isArray(json[0])
  ) {
    // valid input
    for (const [index, key] of Object.keys(json[0]).entries()) {
      // create a column vector
      let col = json.map((row) => row[key]);
      // infer the data type from the first elem of the column
      if (typeof col[0] === "number") {
        col = await new webR.RDouble(col);
      } else if (typeof col[0] === "string") {
        col = await new webR.RCharacter(col);
      } else {
        throw new Error(
          "Unsupported data type in input data to jsonToDataframe: ",
          col[0],
          typeof col[0]
        );
      }
      await webR.objs.globalEnv.bind(`v_${index}`, col);
    }
    // create df from column variables
    await webR.evalR(
      `${globalVarName} <- data.frame(${Object.keys(json[0])
        .map((_, index) => `v_${index}`)
        .join()})
       colnames(${globalVarName}) <- c(${Object.keys(json[0])
        .map((colName) => "'" + colName + "'")
        .join(",")})
      `
    );
    return globalVarName;
  } else {
    throw new Error("Invalid input. Input data has to be an array of objects.");
  }

  function makeid(length) {
    let result = "";
    const characters =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    const charactersLength = characters.length;
    let counter = 0;
    while (counter < length) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
      counter += 1;
    }
    return result;
  }
}
```

It's also shown at the end of this notebook: https://observablehq.com/d/9be88c7a4d7b0edd

**Comment by bugzpodder** [comment]
I do this:
```
    const df_json = await new webR.RObject(JSON.stringify(data));
    const env = await new webR.REnvironment({ df_json });
```

and 
```
library(jsonlite)
df <- as.data.frame(fromJSON(df_json))
```

**Comment by chrispahm** [comment]
Thanks for @bugzpodder for sharing! That’s certainly a lot less code, but serializing + parsing usually comes with a lot of overhead. Especially with large objects it tends to be slower, will do a few performance checks later

**Comment by WillemSleegers** [comment]
Both solutions don't seem ideal. Isn't there a way to construct a JavaScript object and convert it to a data frame in R, similar to `WebR.RList`?

**Comment by georgestagg** [comment]
> Isn't there a way to construct a JavaScript object and convert it to a data frame in R, similar to `WebR.RList`?

Not yet, but it's on our radar. The reason is that an R data frame is not a fundamental object, it's an R list object underneath.

We would like to support this workflow, though, and have reserved passing JavaScript objects of the style `{ foo: [1,2] , bar: [3,4]}` to the `RObject` constructor so that we can use that for exactly this purpose in the future.
