### ISSUE TITLE
(Inline) R Documentation?

### ISSUE THREAD

**Issue by rrmn** [r-wasm/webr#310]
One of the *best things* about RStudio is the inline package and function documentation available at any point. It's a feature not matched in any language / IDE combo I've encountered. (It's also what's missing for me sorely in Jupyter)

Any plans to add it later on? Or is it already baked in and I've missed it?

### RStudio
<img width="632" alt="Screenshot 2023-10-26 at 12 22 31" src="https://github.com/r-wasm/webr/assets/14080347/9e9ab80f-eaaf-408a-9005-7608fe1c2140">
<img width="264" alt="Screenshot 2023-10-26 at 12 22 09" src="https://github.com/r-wasm/webr/assets/14080347/2c054ca8-4c98-4481-a474-1f30f61cff54">

### WebR Online Demo
<img width="693" alt="Screenshot 2023-10-26 at 12 22 51" src="https://github.com/r-wasm/webr/assets/14080347/c7925e07-c644-4245-a211-6ff7f7bd257d">
<img width="690" alt="Screenshot 2023-10-26 at 12 22 56" src="https://github.com/r-wasm/webr/assets/14080347/715d0c2c-455a-4d3b-a7d6-208ef7567562">

**Comment by georgestagg** [comment]
Thanks for bringing this up, I really appreciate the feature suggestion!

Unfortunately, I think that kind of advanced tooltip documentation is out of scope for the webR online demo. The demo is intended mostly to show the things that can be done by integrating webR with other existing JavaScript projects. For example, the code editor is [CodeMirror](https://codemirror.net), and the completion engine is the existing [rcompgen](https://rdrr.io/r/utils/rcompgen.html) feature in R.

Getting this to work well would require significant engineering time spent on expanding those two external projects, both to get the correct documentation out of R and then display the content in CodeMirror. However, any other projects using webR without these external JS libraries wouldn't see the benefit of that development time.

So, while I do think this is technically possible and a good idea (as RStudio has shown us), I am going to close this issue as out of scope, at least for the time being.
