### ISSUE TITLE
Running local demo repl in an iframe - error

### ISSUE THREAD

**Issue by psychemedia** [r-wasm/webr#315]
Hi

I'm trying to run the demo repl via an iframe using a local copy of the index, css and js files.

I had to rename the .mjs file to .js (the server I'm using doesnlt serve .mjs with the corrrect mime type), but now I'm getting an error:

```bash
Uncaught TypeError: parent.set is not iterable
    at define (repl.js:48737:29)
    at repl.js:48993:16
define @ repl.js:48737
(anonymous) @ repl.js:48993
```

```javascript
 /**
  Define a new tag. If `parent` is given, the tag is treated as a
  sub-tag of that parent, and
  [highlighters](#highlight.tagHighlighter) that don't mention
  this tag will try to fall back to the parent tag (or grandparent
  tag, etc).
  */
  static define(parent) {
    if (parent === null || parent === void 0 ? void 0 : parent.base)
      throw new Error("Can not derive from a modified tag");
    let tag = new Tag([], null, []);
    tag.set.push(tag);
    if (parent)
      for (let t2 of parent.set) //ERROR HERE
        tag.set.push(t2);
    return tag;
```

Any pointers to an easy fix? *(I'm an educator/end user rather than a js/ts developer...)*

**Comment by georgestagg** [comment]
Hi,

I've not seen that one before, I suspect it's probably related to the renaming from `.mjs` to `.js` - though I am not sure.

If your server cannot send the correct MIME type for `.mjs` files, perhaps you could embed the webR Demo website directly instead? This should work if you are not planning to change any of the internal JS/TS code.

```html
<iframe width="75%" height="75%" src="https://webr.r-wasm.org/latest/"></iframe>
```

Previously, this only worked with versioned webR URLs such as `https://webr.r-wasm.org/v0.2.1/`, but as of this morning it should also work with the `/latest` URL.

**Comment by psychemedia** [comment]
Hi  - yes, I tried with pulling in the file from here, and that does seem to work ok; now I just have to try to persuade our IT folk to let me serve `.mjs` with an appropriate MIME-type. Thanks..
