### ISSUE TITLE
ggplot seems to only produce output when you use writeConsole

### ISSUE THREAD

**Issue by christianp** [r-wasm/webr#322]
This has taken me a full day to work out!

I'm trying to use the latest webR, and noticed that while normal plots work, ggplot doesn't produce any output. I've finally narrowed it down to the fact that when I run my code through `webR.writeConsole` it works, but with `webR.evalR` or `shelter.captureR`, it doesn't.

So is ggplot waiting for something from the prompt, internally?

I've made a minimal example at https://joyous-jelly-kilometer.glitch.me/, based on the plotting demo from the docs. I gradually copied bits of code from the REPL app, which does work, until I managed to get some output.

**Comment by georgestagg** [comment]
Plots in `ggplot` need to be [explicitly printed](https://ggplot2.tidyverse.org/reference/print.ggplot.html). Try saving the result of the ggplot call to an object, `g`, then running `print(g)`. 

Or, turn on R's autoprint mechanism with:

```
webR.evalR(code, { withAutoprint: true });
```

**Comment by christianp** [comment]
doh! Thanks.
