### ISSUE TITLE
`webr::global_prompt_install()` not working with `webR.evalR()`

### ISSUE THREAD

**Issue by christianp** [r-wasm/webr#324]
The WebR support package has a function `webr::global_prompt_install()` which will interactively prompt you to install a package before loading it.
Is there a way of getting WebR to automatically install packages without a prompt? Or could I write my own shim round `library()` to do this?

**Comment by georgestagg** [comment]
The [`webr::global_prompt_install()`](https://docs.r-wasm.org/webr/latest/api/r.html#global_prompt_install) command takes an argument `show_menu`. When this is set to `FALSE`, webR should skip the menu and just attempt to download the package instead.

**Comment by christianp** [comment]
Ah, thanks!

**Comment by georgestagg** [comment]
> [..] install packages in an allowed list [...]

Ah, I just saw this part of the question! There's no support for an allow-list, I think you'd have to implement that yourself.

You might be able to use [`renv::dependencies()`](https://rstudio.github.io/renv/reference/dependencies.html) as an alternative to shimming `require()` and `library()`, then once you have your list filter it down and use `webr::install()` in R or [`webR.installPackages()`](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#installpackages).

**Comment by christianp** [comment]
Hrm: when I run that, I get "WebRWorkerError: should not be called with handlers on the stack".
Here's a minimal page that just loads webR and tries to run `webr::global_prompt_install()`: https://darkened-opalescent-asphalt.glitch.me/
Clearly I'm doing something wrong, but what?

**Comment by georgestagg** [comment]
Ah yes, there's a gap in documentation here, sorry. To install the new global error handler we have to temporarily turn off webR's other built-in error and warning capturing handlers.

Try with:
```
await webR.evalRVoid(`webr::global_prompt_install(FALSE)`, { withHandlers: false });
```

I'll reopen this to remind me to document it.

**Comment by georgestagg** [comment]
I've done some experimentation, and I can't seem to get this working with `evalR()`, though I'm sure it worked at some point. Possibly it breaks when using the `PostMessage` channel since that implements a limited version of the built-in R REPL.

It does seem to work when using `writeConsole()` and pumping `.read()` for output. But with that method, you can't get R object references back, just output messages.

```
  const webR = await new WebR();
  await webR.init();
  await webR.evalRVoid(`webr::global_prompt_install(FALSE)`, { withHandlers: false });
  await webR.writeConsole(`library(dplyr)`);
  for (;;) {
    const output = await webR.read();
    switch (output.type) {
      case 'stdout':
        console.log(output.data)
        break;
      case 'stderr':
        console.log(output.data);
        break;
      case 'prompt':
        console.log(output.data);
        break;
      default:
        console.error(`Unimplemented output type: ${output.type}`);
        console.error(output.data);
    }
  }
```
(https://terrific-coordinated-parrot.glitch.me/)
