### ISSUE TITLE
Inconsistent outer order-why？

### ISSUE THREAD

**Issue by zhangwenda0518** [r-wasm/webr#332]
Hello, author, I'm using PieDonut to draw the rising sun. I'm a beginner. I'm excited to draw the figure I want, but I find that the inner ring and the outer ring can't correspond well, but I don't know how to adjust it. Another thing, can you add the function of custom color? Sometimes we want to adjust its color to be consistent with other pictures.
I see the color solution here, I hope you can add this function. （https://www.coder.work/article/7794816）
thanks！

PieDonut(test1,aes(pies=type1,donuts=type2,count=num),title = "Repeats in ",
         labelposition=2,ratioByGroup=FALSE,
         pieLabelSize=4,donutLabelSize=3)

![image](https://github.com/r-wasm/webr/assets/77140740/8a340f25-dacf-4a1c-8f67-8b14946ba172)

mydata
type1	type2	num
LTR	Copia	22.44
LTR	Gypsy	10.72
LTR	unknown	3.13
nTIR	helitron	3.15
TIR	CACTA	3.57
TIR	Mutator	4.61
TIR	hAT	3.08

**Comment by georgestagg** [comment]
Hi,

Your question is related to a different R package named `webr`. That package is the one available through CRAN and provides the `PieDonut()` function.

Please submit your issue to their GitHub page here: https://github.com/cardiomoon/webr
