### ISSUE TITLE
Webr is not updating as i updated the code?

### ISSUE THREAD

**Issue by ravinder387** [r-wasm/webr#355]
when i update ui.R and server.R file it doesn't show the updated things when refreshing. I need to change port. Is there any way to re-register every time service worker
![2024-01-25 (3)](https://github.com/r-wasm/webr/assets/21985515/647f8d17-98ae-48c8-a31a-86293808857d)

**Comment by georgestagg** [comment]
There are two ways to clear the browser's service worker with browser dev tools:

* Under "Application", stop the service worker `httpuv-serviceworker.js` and then click "Unregister". Then, ensure "disable cache" is checked under the "Network" tab. This way, it should be re-fetched and re-started from source next time the page loads.

* This might be Chrome only, but with devtools open right click the "Refresh" icon and click "Empty cache and hard reload". There should be some similar scheme in Firefox's web developer tools to clear your cache and reload the page from a clean slate.
