### ISSUE TITLE
Unable to mount image error when loading shiny library 

### ISSUE THREAD

**Issue by maek-ies** [r-wasm/webr#366]
When trying to load shiny library in webR REPL demo, following error occurs:

Error in mount(mountpoint, data_url) : 
  Unable to mount image, `/usr/lib/R/library/Rcpp` is already mounted.

![error_webr](https://github.com/r-wasm/webr/assets/151060752/40c22204-a38f-4ca3-82eb-1d401541a1a8)

I tried to clear the history and cache and also other browser (happens in Chrome and Edge too). Actually, the code was working fine until I tried to perform empty cache and hard reload command to make sure latest version of the shinylive app is loaded for my project.

**Comment by georgestagg** [comment]
Related to #361. WebR is attempting to mount the same package package multiple times.

I'm unable to reproduce as of yet at my end. Once I can recreate the issue I'll be able to debug further.

**Comment by maek-ies** [comment]
> Related to #361. WebR is attempting to mount the same package package multiple times.
> 
> I'm unable to reproduce as of yet at my end. Once I can recreate the issue I'll be able to debug further.

Thanks a lot, @georgestagg. After an additional couple of rounds of clearing cache it seems to work now. Maybe just a coincidence but started to first work when loading https://shinylive.io/r/examples/ page. 

Could it be that it is a consequence of updating r-wasm packages yesterday? If I recall correctly, in some of your other posts you mentioned invalidating packages...

**Comment by maek-ies** [comment]
This is related to posit-dev/r-shinylive#68, where the same issue appeared again after there was fix of small issue with the package repository used by shinylive. I was able to solve by ticking disable cache in chrome developer tolls view and reloading app once. Now works again even with disable cache again unticked. The issue can be closed.
