### ISSUE TITLE
Cannot install the 'devtools' package

### ISSUE THREAD

**Issue by MaybeJustJames** [r-wasm/webr#376]
This can be reproduced on the interactive demo page (https://docs.r-wasm.org/webr/latest/) with this snippet:

```R
webr::install('devtools')
library(devtools)
```

Which results in this error:
```
Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: NULL
  error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

**Comment by georgestagg** [comment]
This is the same issue as #374, so I will close this as a duplicate in favour of that thread. See the discussion there for further details, but the package should load in non-Safari browsers with:

```
options(expressions = 5000)
webr::install('devtools')
library(devtools)
```

Note that `curl` is not available in webR, so loading and trying to use `devtools` will generate unrelated errors about `curl`. Also note that an R development toolchain does not exist in webR itself, so much of `devtools` functionality will be unavailable.
