### ISSUE TITLE
how / when do packages at repo.r-wasm.org get updated?

### ISSUE THREAD

**Issue by isbool** [r-wasm/webr#385]
Hey, after opening an issue on the GitHub of the developers of the [vegan ](https://vegandevs.r-universe.dev/vegan)package (it couldn't compile to wasm due to issues of the compiler with dynamic memory allocation in Fortran, the developers changed the code to statically allocate memory on the affected parts) they released a [new version](https://vegandevs.r-universe.dev/bin/emscripten/contrib/4.3/vegan_2.6-5.tgz) which compiles to wasm. 
Its up on[ r-universe](https://vegandevs.r-universe.dev/vegan) 2-3 days now but i see it still hasnt been added to repo.r-wasm.org.
I wanted to ask what's the process of getting it to update there.

**Comment by georgestagg** [comment]
The <repo.r-wasm.org> repository follows CRAN releases but is updated less often. Currently the repository is frozen in preparation for the webR 0.3.0 release, expected within the next week or so.

As webR 0.3.0 is released, repo.r-wasm.org will be updated at the same time with the latest version of all Wasm compatible packages on CRAN. In the meantime, I recommend using R-Universe's binaries to load the vegan package.

I'm going to close this issue, as it's not directly a package request or a bug in webR, but feel free to comment here after the release of webR 0.3.0 if the package does not appear in the repo.
