### ISSUE TITLE
Reading a CSV with data.table::read fails claiming the file is empty

### ISSUE THREAD

**Issue by MaybeJustJames** [r-wasm/webr#387]
Here is a reproduction:

```R
webr::install("data.table")
chisq <- data.frame(A = c(1, 0.5, 0.2),
                    B = c(0.1, 0.2, 0.3),
                    C = c(0.54, 0.1, 0.05))
print(chisq)
data.table::fwrite(chisq, file = "chisq.csv", col.names=FALSE)
readLines("chisq.csv")
data.table::fread("chisq.csv")
```

I expect to read the CSV with `data.table::fread`. On desktop I get this output:
```bash
$ $ Rscript reprod.R 
    A   B    C
1 1.0 0.1 0.54
2 0.5 0.2 0.10
3 0.2 0.3 0.05
[1] "1,0.1,0.54"   "0.5,0.2,0.1"  "0.2,0.3,0.05"
      V1    V2    V3
   <num> <num> <num>
1:   1.0   0.1  0.54
2:   0.5   0.2  0.10
3:   0.2   0.3  0.05
```

In WebR I get this output:

```
[1] "test"
    A   B    C
1 1.0 0.1 0.54
2 0.5 0.2 0.10
3 0.2 0.3 0.05
[1] "1,0.1,0.54"   "0.5,0.2,0.1"  "0.2,0.3,0.05"
Error: File is empty: chisq.csv
```

**Comment by MaybeJustJames** [comment]
[This](https://github.com/Rdatatable/data.table/blob/3eefbcaa47a1c2fc28037574aee27992d083750e/src/fread.c#L1385) looks like a potential culprit?

**Comment by georgestagg** [comment]
This is related to https://github.com/Rdatatable/data.table/issues/5969

I tested a new build of the package on a pre-release version of webR 0.3.0 and it is working there:

![Screenshot 2024-03-20 at 13 49 26](https://github.com/r-wasm/webr/assets/982548/675118b2-471e-4d54-b2e0-270cf51aca9b)

So I am confident that once webR 0.3.0 is released and the default webR package repo is updated, the problem should go away. Still, I will leave this issue open until then.

**Comment by georgestagg** [comment]
This now seems to be fixed in both https://webr.r-wasm.org/latest/ and https://webr.r-wasm.org/v0.3.1/.
