### ISSUE TITLE
use languageserver protocol in R repl app

### ISSUE THREAD

**Issue by seanbirchall** [r-wasm/webr#389]
It doesn't look like the webR repl app is using lsp currently. I see that the `languageserver` R package is currently available via https://repo.r-wasm.org/. 

I believe the repl app is using codemirror which does support lsp. Currently I'm trying to do something similar with Ace, but curious if lsp for the repl app is currently on the roadmap.

**Comment by georgestagg** [comment]
There are currently no plans to add LSP support to the basic webR app included as part of this repository.

The intention for that app is to demonstrate and support basic 4-pane style data science in the browser, but not to be a fully-fledged IDE with complex development features such as support for LSP. When presenting the app, I say: "For example, no one will be doing R package development here".

However, I do agree that this should be possible in principle. I just think such a feature would be better served as part of a downstream repository or project, where more complex systems can be added without compromising the relative simplicity of the included demo app.
