### ISSUE TITLE
[Question] webr - quarto - how to control the size of the code in the webr window

### ISSUE THREAD

**Issue by rainer-rq-koelle** [r-wasm/webr#424]
Apologies, I failed to find a better place to post this question. I am currently exploring using webr in Quarto for some introductory material on R and ggplot for co-workers. 
I am amazed by the possibilities - however, I have to admit that the "magic of the workings" is not fully transparent to me. 
From a readability perspective, I would like to have the webr-windows blend nice(r)ly to the surrounding text.

How can I control the fontsize of the code in the webr window of the rendered web-page?

Thanks for any pointer.

**Comment by coatless** [comment]
@rainer-rq-koelle Feel free to open an issue: <https://github.com/coatless/quarto-webr/issues/new/choose> !

If it helps, we have documentation on styling elements available here: 

<https://quarto-webr.thecoatlessprofessor.com/qwebr-theming.html>

There is also a great example of custom styling by James Goldie (@jimjam-slam) [here](https://jamesgoldie.dev/writing/your-new-r-package-webr/).
 
- Quarto document source: [your-new-r-package.qmd](https://github.com/jimjam-slam/jamesgoldie-dev/blob/6b60b2e42c6e21eb1ed8ae390f108592bb48d98c/writing/your-new-r-package-webr/index.qmd)
- Custom CSS: [webr.css](https://github.com/jimjam-slam/jamesgoldie-dev/blob/6b60b2e42c6e21eb1ed8ae390f108592bb48d98c/writing/your-new-r-package-webr/webr.css)

**Comment by rainer-rq-koelle** [comment]
Thanks for the pointer(s). I fully understand. Servus, RQ
