### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by 027xiguapi** [r-wasm/webr#430]
![1717139047474](https://github.com/r-wasm/webr/assets/31228055/f5fa0b24-f907-4623-a9df-061fc9e65f75)
Chromium94.0.4606.71

open https://webr.r-wasm.org/latest/

**Comment by 027xiguapi** [comment]
I found the reason,  globalThis.document is undefined
![image](https://github.com/r-wasm/webr/assets/31228055/3b361328-e95b-45a3-896c-4210250fc6ee)

**Comment by 027xiguapi** [comment]
WebAssembly.Tag is undefined

**Comment by 027xiguapi** [comment]
![image](https://github.com/r-wasm/webr/assets/31228055/352a33e5-4f9c-4c76-902d-47c37c0eb418)

**Comment by georgestagg** [comment]
Thank you for taking the time to debug this.

Unfortunately, `WebAssembly.Tag` is used for [WebAssembly exceptions](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Exception). WebR is built to use Wasm exceptions, and so this feature is absolutely required for the latest version of webR to function.

You might be able to use very old builds of webR, from before we used Wasm exceptions (e.g. https://webr.r-wasm.org/v0.1.0/), but I cannot say for sure.

It looks like Chromium 94.0.4606.71 was released in September 2021, which is quite old in terms of browser updates. The latest release is 128.0.6546.0. If you can upgrade to a newer version of Chromium, it should run webR better.

We don't plan to support such older browsers going forward, and so I'm going to close this issue as not planned.
