### ISSUE TITLE
webr support for {gt} package 

### ISSUE THREAD

**Issue by rainer-rq-koelle** [r-wasm/webr#431]
Congrats! I am just fascinated by what can be done with wasm/webr. I embrace tinkering with it and see a huge potential for teaching/demoing "many things R coding" related. However, I admit that the "magic of its working" is outside my comprehension. 

Following some of the tutorials/introductory material, I wanted to use webr to showcase {gt}.     
When setting up the Quarto document and rendering it, I hoped that the following would work like a charm. I have failed to find any meaningful pointer(s). 

Question on stackoverflow: https://stackoverflow.com/questions/78534930/webr-and-gt-throws-error-error-browser-must-be-a-non-empty-character-stri

The error message thrown from the web-r chunk output reads:  ```Error: 'browser' must be a non-empty character string```

Quarto yaml:
---
engine: knitr
filters:
  - webr
webr:
  packages: ['dplyr','gt']
---

And then let's trial {gt}

```{webr-r}
my_tbl <- mtcars[1:10,] |> tibble()

my_tbl |> gt()
```
<img width="620" alt="Screenshot 2024-06-01 at 09 21 34" src="https://github.com/r-wasm/webr/assets/17096612/5df91905-8d14-45f1-af53-fcc9f74ef81f">

Calling `?gt` in the webr-container on a rendered webpage results in the standard (embedded) help page for {gt}. Thus, the package {gt} appears to be loaded and available in the {webr} session.

Could someone put me on the right track? Thanks.

**Comment by timelyportfolio** [comment]
@rainer-rq-koelle I am not on the official team, but I do have some experience with `html` and `R`, so I'll try to chime in with some hopefully helpful context.  This issue relates to the fact that `webr` does not have a `browseURL` equivalent viewer (such as RStudio Viewer tab in RStudio or chrome/edge/firefox).

The [`gt:::print.gt_tbl`](https://github.com/rstudio/gt/blob/master/R/print.R#L36-L46) method in an interactive session will effectively create an `html` file which then opens with `browseURL` except we do not have a browser in `webr`.  For instance, `htmlwidgets` use a very similar mechanism, and these also will not work in a webr Quarto context.

This is a challenging issue, but there might be some hope.  I started to explore how we might resolve with `htmlwidgets` in this [post](https://www.jsinr.me/2023/12/11/htmlwidgets-webr-experiment/), but unfortunately this is not automated and requires special effort customized to each htmlwidget.  Using an example from `gt` we can see that we ultimately can get the `html` with `view=FALSE` (similar to producing `gt` in Rmd or Quarto without `webr`).

```
gt:::print.gt_tbl(exibble |> gt(), view = FALSE)
```

![image](https://github.com/r-wasm/webr/assets/837910/3d704fc0-e289-44ff-90fc-fab0ed29a4df)

**Comment by georgestagg** [comment]
@timelyportfolio is correct. Unfortunately webR does not currently support displaying `htmltools` or `htmlwidgets` output in the containing web page. AFAIK this is unsupported in the community-driven `quarto-webr` extension (https://github.com/coatless/quarto-webr) right now too, though it might be on their radar for future work.

----

Saying that... I am right now working on significantly improving webR and Quarto integration, including support for displaying HTML widgets from webR in Quarto documents, without any of the overhead work mentioned above. Here is a preview:

![Screenshot 2024-06-02 at 18 10 30](https://github.com/r-wasm/webr/assets/982548/1fdd0adf-a9ec-45f0-a2a7-80abd7fc9d08)

This new framework is not yet ready for release, but I'll be continuing to work on it and will release more information about it in the coming weeks.

**Comment by timelyportfolio** [comment]
@georgestagg this looks amazing!!  Please let me know how I can help.  I am more than happy to support in any way possible.

**Comment by georgestagg** [comment]
Closing as this should now work in the REPL. The new extension I mention above for use in Quarto should hopefully be available by the end of this week.
