### ISSUE TITLE
Output buffer difference between `Shelter.captureR()` and `Console()`

### ISSUE THREAD

**Issue by coatless** [r-wasm/webr#434]
Relevant ticket: https://github.com/coatless/quarto-webr/issues/208

The main issue is the lines from writing a `data.frame` with `gt()` to STDOUT are exceeding the buffer associated with `Shelter.captureR()` but not `Console()`. 

So, the webR REPL is able to correctly output the results; but, the `Shelter.captureR()` is not able to. 

```r
webr::install("gt")
gt::gt(mtcars) |> print(view = FALSE)
```

Under REPL: 

<img width="1233" alt="Screenshot showing the `gt()` class being output under the webR REPL environment that uses Console to process output" src="https://github.com/r-wasm/webr/assets/833642/4198d648-d3af-4afa-a1ac-0c97441f816b">

Under `Shelter.captureR()`:

<img width="585" alt="Screenshot showing the `gt()` class being output under a `quarto-webr` code cell that uses `Shelter.captureR()` to obtain and process output" src="https://github.com/r-wasm/webr/assets/833642/35fd0413-a1d6-4dbc-8a98-67b87976840e">

**Comment by georgestagg** [comment]
This is a consequence of how R output is captured when running in the non-console context.
See:

https://github.com/r-wasm/webr/blob/c07d8997ddbb58f63002e8d46792be54edcd134c/packages/webr/src/outputconnection.c#L46-L51

and:

https://github.com/r-wasm/webr/blob/c07d8997ddbb58f63002e8d46792be54edcd134c/packages/webr/src/outputconnection.c#L98-L105

----

We should consider:

* Increasing `BUFSIZE` in the short term.
* Adding a mechanism to dynamically grow `output_con_data` in the longer term.

----

The OP issue would also be solved by handling htmlwidget output correctly, avoiding need to capture raw HTML and `output: asis`. I'm working on this separately as part of our previously discussed Quarto/webR integration project.
