### ISSUE TITLE
R API docs not rendered 

### ISSUE THREAD

**Issue by JosiahParry** [r-wasm/webr#439]
At the moment there isn't any way to read the WebR R package documentation (that I can find) outside of the source code. The hyperlinks internal to the webR documentation point to https://docs.r-wasm.org/webr/latest/api/r.html which is empty.

Where might we read the docs for the R package? 

Thanks!

**Comment by georgestagg** [comment]
Thanks for reporting! It looks like this broke somewhere between https://docs.r-wasm.org/webr/v0.3.2/api/r.html and https://docs.r-wasm.org/webr/v0.3.3/api/r.html.

It should now be fixed, as of 297249f872c624965068a9dd8bffe737bbffa42e.

**Comment by georgestagg** [comment]
AWS seems to have caught up, at least in my region. Closing.
