### ISSUE TITLE
Throw an error if loading worker URL fails

### ISSUE THREAD

**Issue by georgestagg** [r-wasm/webr#461]
Network errors will throw, but e.g. 403 doesn't. At startup we should catch unexpected HTTP responses and throw.

**Comment by Dual-Ice** [comment]
Hello, I see that you modify code to throw error when resource(web-worker for example) is failed to load (404 or whatever). But I try to catch it:
Using in vue component:  
```
methods: {
    async initializeService(url) {
        try {
            const webR = new WebR({baseUrl: url});
            await webR.init();
            console.log('WebR initialized');
        } catch (e) {
            console.error('Init error:', e);
        }
```
Where url is broken and I never catch error.
