### ISSUE TITLE
feature request: shareable link with pre-defined code for webr.r-wasm.org

### ISSUE THREAD

**Issue by pawelru** [r-wasm/webr#468]
(not sure if that's the right repo - feel free to transfer where appropriate)

Something similar to what we have for shinylive when the code compressed and added to the url

https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAHTABUALASwGcACAMzilIFcAnOGyIc2LZhACeAGyYA3IazYBzQTwCEbAOpFe0gCZsmpNgCMhqIixZNT0oaSJsGUBW1IMhLWEI5F+bADucKb8APy0YAC+ALpAA

**Comment by parmsam** [comment]
This could help support a future R (chat) assistant similar to the shiny assistant that @wch presented today at Posit Conf.

**Comment by georgestagg** [comment]
I agree, this would be a great feature.

I'm closing this as a duplicate of https://github.com/r-wasm/webr/issues/356, we'll continue to track things there.
