### ISSUE TITLE
Building an R package library: file permissions prevent add_pkg from working

### ISSUE THREAD

**Issue by richarddmorey** [r-wasm/webr#475]
I'm following the instructions [in the documentation](https://r-wasm.github.io/rwasm/articles/mount-fs-image.html#building-an-r-package-library) to create a package library, after having (successfully, I think) followed the instructions for [setting up the WebAssembly toolchain using the Docker container](https://r-wasm.github.io/rwasm/articles/rwasm.html).

However when running `rwasm::add_pkg` I get file permissions errors, such as `Error: [EACCES] Failed to set permissions for directory './repo': permission denied`.

As far as I know, I've followed the instructions to the letter.

System info: Mac M1 Pro, Sonoma 14.6.1 (23G93)

Here is the directory listing from within the working directory after creating the `output` folder and before running the `docker` command:
```
% ls -la
total 0
drwxr-xr-x  3 saprm3  staff  96 29 Aug 15:41 .
drwxr-xr-x  3 saprm3  staff  96 27 Aug 11:28 ..
drwxr-xr-x  2 saprm3  staff  64 29 Aug 15:41 output
```

I then continue the instructions, but I get an error about directory permissions:

```
% docker run -it --rm -v ${PWD}/output:/output -w /output ghcr.io/r-wasm/webr:main R
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rwasm)
Targeting Wasm packages for R 4.4.1
With `WEBR_ROOT` directory: /opt/webr
With `EMSCRIPTEN_ROOT` directory: /opt/emsdk/upstream/emscripten
> rwasm::add_pkg("knitr")
v Updated metadata database: 2.44 MB in 7 files.
v Updating metadata database ... done
Processing 1 package(s).
Error: [EACCES] Failed to set permissions for directory './repo': permission denied
>
```

If I quit R, then change the permissions on `repo` (`chmod ugo+wx output/repo`), re-run the `docker` command to start R again, then try `rwasm::add_pkg` again, it will apparently progress to the next step, and then yield another error:

```
Error: [EACCES] Failed to set permissions for directory './repo/src': permission denied
```

Is there some way of setting the permissions on `output` to allow the R process to work correctly?

**Comment by georgestagg** [comment]
Hi @richarddmorey,

I have seen this once before, but unfortunately I was never able to figure out exactly what is going on. I was able to work around the issue, though the method is a little messy:

First, start the docker image without the volume mount argument:

```
docker run -it --rm -w /output ghcr.io/r-wasm/webr:main R
```

Now, leave this running and open a new terminal window or tab. Query docker for running containers, looking for this one. Make a note of the "CONTAINER ID".

```
$ docker ps
CONTAINER ID   IMAGE                      COMMAND   CREATED          STATUS          PORTS     NAMES
0b10df69bb2f   ghcr.io/r-wasm/webr:main   "R"       38 seconds ago   Up 38 seconds             upbeat_shaw
```

Next, return to the first terminal and do the work required. This will write to the virtual `/output` inside the container, rather than to the `output` subdirectory.

```
> library(rwasm)
Targeting Wasm packages for R 4.4.1
With `WEBR_ROOT` directory: /opt/webr
With `EMSCRIPTEN_ROOT` directory: /opt/emsdk/upstream/emscripten
> rwasm::add_pkg("knitr")
v Updated metadata database: 2.44 MB in 7 files.
v Updating metadata database ... done
Processing 1 package(s).
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
trying URL 'https://packagemanager.posit.co/cran/latest/src/contrib/knitr_1.48.tar.gz'
Content type 'binary/octet-stream' length 582337 bytes (568 KB)
==================================================
downloaded 568 KB

v Updated metadata database: 1.40 MB in 1 file.                                        
v Updating metadata database ... done                                     
                                                                          
> Will install 4 packages.
[...] 
v 4 deps: added 4, dld 4 (297.18 kB) [42.8s]                       
* installing *source* package 'knitr' ...
** package 'knitr' successfully unpacked and MD5 sums checked
[...]
* creating tarball
packaged installation of 'knitr' as 'knitr_1.48_R_x86_64-pc-linux-gnu.tar.gz'
* DONE (knitr)
Packaging: knitr_1.48.data
Processing packages:
  /output/repo/src/contrib/knitr_1.48.tar.gz
done
Processing packages:
  /output/repo/bin/emscripten/contrib/4.4/knitr_1.48.tgz
done
```

Once finished, go back to your other terminal and run the following docker command to copy out the files from `/output` inside your container to the `output` directory in the current directory. Be sure to replace "0b10df69bb2f" with your own CONTAINER ID that you noted above.

```
docker cp 0b10df69bb2f:/output .
```

**Comment by richarddmorey** [comment]
Thanks, this seems to have worked!
