### ISSUE TITLE
WASM binaries not building consistently

### ISSUE THREAD

**Issue by EduardBel** [r-wasm/webr#489]
Hi,
I am currently trying to build the R library Spectra to WASM, using the provided container (version 0.4.1).
I am following the steps on the [vignette](https://github.com/r-wasm/rwasm/blob/main/vignettes/rwasm.Rmd) to build it. However, most of the times I try, i am getting just the .tgz file as output and fewer times, the additional .data and .metadata files.
Why is it happening? can I use some flag to force the creation of these two files?
I would rather build my libs for R v4.3.x

**Comment by georgestagg** [comment]
We're in the process of migrating to a packaging system that requires only the `.tgz` file.

In the meantime, you should try using an older docker image release to build you packages:

```
docker pull ghcr.io/r-wasm/webr:v0.3.3
docker run -it --rm -v ${PWD}/output:/output -w /output ghcr.io/r-wasm/webr:v0.3.3 R
```

The full list is at: https://github.com/r-wasm/webr/pkgs/container/webr/versions

**Comment by EduardBel** [comment]
Thanks for your early reply.
Unfortunately, I had already tried that:

- docker pull ghcr.io/r-wasm/webr:v0.3.3
- mkdir -p output
- docker run -it --rm -v ${PWD}/output:/output -w /output ghcr.io/r-wasm/webr:v0.3.3 R
- install.packages("pak")
- pak::pak("r-wasm/rwasm")
- library(rwasm)
- build("Spectra")

the output I am getting is:
```
...
v 20 deps: kept 2, added 16, dld 16 (20.15 MB) [57.2s]                    
* installing *source* package 'Spectra' ...
** using non-staged installation
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
* creating tarball
packaged installation of 'Spectra' as 'Spectra_1.12.0_R_x86_64-pc-linux-gnu.tar.gz
* DONE (Spectra)
Appending virtual filesystem metadata for: Spectra_1.12.0.tgz
```
![image](https://github.com/user-attachments/assets/26817770-1e53-4211-a2d8-a133da31be2d)

Should I be getting the 3 files (tgz, data and metadata) doing exactly this?

**Comment by georgestagg** [comment]
Ah, yes, I see what is happening. Please try the same procedure but installing the older version of the `rwasm` package with the following modified command:

```
pak::pak("r-wasm/rwasm@v0.1.0")
```

**Comment by EduardBel** [comment]
Problem solved! Thank you very much :D
