### ISSUE TITLE
brms not running in browser

### ISSUE THREAD

**Issue by lauralambert99** [r-wasm/webr#503]
brms will not compile a very simple model within the browser - it should be a supported package, and it has been called in the yaml header.  Not sure if I have just missed something or if this is a known issue.

**Comment by georgestagg** [comment]
Compiling a model with `brms` requires [rstan](https://mc-stan.org/users/interfaces/rstan). Unfortunately that package is not yet available in webR. It is likely that the Stan system dependency will need to be specially compiled for WebAssembly.

I've added these packages to the overall package request issue at #383. I'm going to close this particular issue. It will say "not planned", but in reality we'll track `brms` and `rstan` along with the other R packages that have requested over in that thread.
